# Generated by Django 6.0 on 2026-04-28 22:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("cnh", models.CharField(max_length=20, unique=True)),
                ("validade_cnh", models.DateField(blank=True, null=True)),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("modelo", models.CharField(max_length=100)),
                ("marca", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "ano",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2027),
                        ],
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("carro", "Carro"),
                            ("moto", "Moto"),
                            ("caminhao", "Caminhão"),
                            ("van", "Van"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("cor", models.CharField(blank=True, max_length=50, null=True)),
                ("chassi", models.CharField(blank=True, max_length=50, null=True)),
                ("renavam", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="veiculos/"),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("manutencao", "Manutenção"),
                            ("inativo", "Inativo"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="UsoVeiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "km_inicial",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "km_final",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="veiculos.motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usos",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uso de Veículo",
                "verbose_name_plural": "Uso de Veículos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("acidente", "Acidente"),
                            ("multa", "Multa"),
                            ("furto", "Furto/Roubo"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("local", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("data", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_andamento", "Em Andamento"),
                            ("finalizado", "Finalizado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("creado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veiculos.motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência",
                "verbose_name_plural": "Ocorrências",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventiva", "Preventiva"),
                            ("corretiva", "Corretiva"),
                            ("trocaoleo", "Troca de Óleo"),
                            ("freios", "Freios"),
                            ("pneus", "Pneus"),
                            ("revisao", "Revisão"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                ("oficina", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "km_veiculo",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("data_manutencao", models.DateField()),
                ("data_proxima", models.DateField(blank=True, null=True)),
                (
                    "km_proxima",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manutencoes",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "ordering": ["-data_manutencao"],
            },
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("crlv", "CRLV"),
                            ("seguro", "Seguro Obrigatório"),
                            ("ipva", "IPVA"),
                            ("licenciamento", "Licenciamento Anual"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("numero", models.CharField(max_length=100)),
                ("data_emissao", models.DateField(blank=True, null=True)),
                ("data_validade", models.DateField()),
                (
                    "documento_file",
                    models.FileField(blank=True, null=True, upload_to="documentos/"),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "ordering": ["data_validade"],
            },
        ),
        migrations.CreateModel(
            name="Despesa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ipva", "IPVA"),
                            ("seguro", "Seguro"),
                            ("multa", "Multa"),
                            ("pedagio", "Pedágio"),
                            ("estacionamento", "Estacionamento"),
                            ("licenciamento", "Licenciamento"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("descricao", models.TextField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("data", models.DateField()),
                ("pago", models.BooleanField(default=False)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="despesas",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Despesa",
                "verbose_name_plural": "Despesas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Alerta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("cnh", "CNH Vencida"),
                            ("ipva", "IPVA Vencido"),
                            ("seguro", "Seguro Vencido"),
                            ("manutencao", "Manutenção Programada"),
                            ("revisao", "Revisão"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_alerta", models.DateField()),
                ("enviado", models.BooleanField(default=False)),
                ("data_envio", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("enviado", "Enviado"),
                            ("concluido", "Concluído"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "ordering": ["data_alerta"],
            },
        ),
        migrations.CreateModel(
            name="Abastecimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "km",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "litros",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valor_litro",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "tipo_combustivel",
                    models.CharField(
                        choices=[
                            ("gasolina", "Gasolina"),
                            ("etanol", "Etanol"),
                            ("diesel", "Diesel"),
                            ("gnv", "GNV"),
                            ("eletrico", "Elétrico"),
                            ("flex", "Flex"),
                        ],
                        max_length=50,
                    ),
                ),
                ("posto", models.CharField(blank=True, max_length=100, null=True)),
                ("data", models.DateField()),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abastecimentos",
                        to="veiculos.veiculo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Abastecimento",
                "verbose_name_plural": "Abastecimentos",
                "ordering": ["-data"],
            },
        ),
    ]
