# Generated by Django 6.0 on 2026-04-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="motorista",
            name="foto",
            field=models.ImageField(blank=True, null=True, upload_to="motoristas/"),
        ),
    ]
