# Generated by Django 6.0 on 2026-05-01 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_despesa_status(apps, schema_editor):
    Despesa = apps.get_model("veiculos", "Despesa")
    Despesa.objects.filter(pago=True).update(status="pago")


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0003_rename_creado_em_ocorrencia_criado_em"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="despesa",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("analise", "Em análise"),
                    ("pago", "Pago"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
        migrations.RunPython(backfill_despesa_status, migrations.RunPython.noop),
        migrations.AddField(
            model_name="motorista",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="perfil_motorista",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="motorista",
            name="veiculo_padrao",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="motoristas_padrao",
                to="veiculos.veiculo",
            ),
        ),
    ]
