# Generated by Django 6.0 on 2026-05-01 15:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("veiculos", "0004_despesa_status_motorista_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abastecimento",
            name="km",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
